### ISSUE TITLE
Feature request: monospaced font for names

### ISSUE THREAD

**Issue by djvanhelmond** [michielappelman/adventleader#3]
Can you make the naming in the leaderboard in monospaced font with some leading spaces or dashes? I like it when the scoring is aligned.

Also can you make the names link to the competitors github?

**Comment by michielappelman** [comment]
@djvanhelmond there's no mention of the Github URL in the JSON, and people can choose their own nickname on the board, so that will not work. _(Unless I do it statically of course, which it uglay)_

Also, I think monospaced fonts are for the terminal and code, not in Spark. Would it be better to prepend the scores and stars, followed by the names?

**Comment by djvanhelmond** [comment]
Spark does not give you the option to properly align the columns in any other way than monospacing
While spark does not support any other option, monospacing is probably the best option.
